# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Box-Kite"
license = "MIT"
licenselink = "https://github.com/jsulak/hugo-theme-box-kite/blob/master/LICENSE.md"
description = "A simple and retro styled theme ported from Hexo"
homepage = "https://github.com/jsulak/hugo-theme-box-kite"
tags = ["blog", "minimal"]
features = ["blog", ""]
min_version = 0.20

[author]
  name = "James Sulak"
  homepage = "https://github.com/jsulak"

# If porting an existing theme
[original]
  name = "Minos"
  homepage = "https://github.com/ppoffice/hexo-theme-minos"
  repo = "https://github.com/ppoffice/hexo-theme-minos"

[params]
  notoc = true